In [1]:
import pandas as pd 
import numpy as np 

import seaborn as sns 
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
df1_oxid = pd.read_csv('Oxid_000.csv')

- 파생변수 : 기존의 변수의 계산식 을 넣거나, 특정 조건에 따라 새로 데이터를 분류해, 새로운 항목으로 만든 값

In [5]:
# 산화막의 thickness에 따라서 보강해야 할 것과 필요없는 것으로 나눠보자
df1_oxid.describe()

,Ox_Chamber,Temp_OXid,ppm,Pressure,Oxid_time,thickness,Lot_Num,Wafer_Num
count,852.00000,852.000000,852.000000,852.000000,852.000000,852.000000,852.000000,852.000000
mean,2.00000,1064.415784,33.202242,0.211374,123.201878,710.926810,16.281690,13.894366
std,0.81265,149.550147,8.494070,0.009067,76.285130,8.082856,9.116841,7.785951
min,1.00000,862.011276,21.070000,0.180000,-6.000000,681.435000,1.000000,1.000000
25%,1.00000,874.756813,22.450000,0.205000,52.000000,706.313000,8.000000,7.000000
50%,2.00000,1069.240209,33.420000,0.213000,116.000000,711.590500,16.000000,14.000000
75%,3.00000,1189.172249,40.452500,0.217000,217.000000,715.595000,24.000000,21.000000
max,3.00000,1339.476675,49.910000,0.229000,291.000000,737.402000,32.000000,27.000000

In [11]:
cond1=df1_oxid['thickness']<700
df1_oxid.loc[cond1, 'reinfor'] = 'reinfor'
df1_oxid.loc[~cond1, 'reinfor'] = 'normal'
df1_oxid.head()

,Ox_Chamber,process,type,Temp_OXid,Vapor,ppm,Pressure,Oxid_time,thickness,No_Die,Lot_Num,Wafer_Num,Datetime,reinfor
0,1,Oxidation,dry,1138.979159,O2,32.80,0.200,62,699.443,NOLSM111,1,1,17-02-2019 PM 9:04:30,reinfor
1,1,Oxidation,dry,1218.184551,O2,31.86,0.194,137,696.792,NOLSM212,1,2,17-02-2019 PM 9:04:30,reinfor
2,1,Oxidation,dry,1062.467808,O2,39.51,0.217,128,705.471,NOLSM313,1,3,17-02-2019 PM 9:04:30,normal
3,1,Oxidation,dry,1114.704773,O2,32.88,0.201,90,710.772,NOLSM414,1,4,17-02-2019 PM 9:04:30,normal
4,1,Oxidation,dry,989.411946,O2,38.11,0.204,98,716.975,NOLSM515,1,5,17-02-2019 PM 9:04:30,normal

In [13]:
df1_oxid['reinfor'].value_counts()

normal     770
reinfor     82
Name: reinfor, dtype: int64

In [16]:
df1_oxid.pivot_table(index='reinfor', values=['Oxid_time','ppm','Pressure','Temp_OXid'])

          Oxid_time  Pressure    Temp_OXid        ppm
reinfor
normal   125.045455  0.211891  1062.494658  33.107623
reinfor  105.890244  0.206524  1082.455629  34.090732

In [18]:
df1_litho=pd.read_csv('Photo_lithography_000.csv')
df1_litho.head()

,lithography_Chamber,Line_CD,Lamp,UV_type,Wavelength,Resolution,Energy_Exposure,No_Die,Lot_Num,Wafer_Num,Datetime
0,1,30.959,Hg-Arc,H,405,516.657,109.769,NOLSM111,1,1,17-02-2019 PM 9:04:30
1,2,29.653,Hg-Arc,H,405,501.894,107.102,NOLSM212,1,2,17-02-2019 PM 9:04:30
2,3,28.063,Hg-Arc,I,365,506.750,110.471,NOLSM313,1,3,17-02-2019 PM 9:04:30
3,1,31.556,Hg-Arc,I,365,537.603,107.072,NOLSM414,1,4,17-02-2019 PM 9:04:30
4,2,31.969,Hg-Arc,I,365,560.574,108.073,NOLSM515,1,5,17-02-2019 PM 9:04:30

In [21]:
cond1=df1_litho['Line_CD']<25
cond2=df1_litho['Line_CD']>55

df1_litho.loc[cond1|cond2, 'Range_check']='check'
df1_litho.loc[~(cond1|cond2), 'Range_check']='normal'

In [22]:
df1_litho['Range_check'].value_counts()

normal    666
check     186
Name: Range_check, dtype: int64

In [23]:
df1_etch=pd.read_csv('Etching_000.csv')
df1_etch.head()

,Unnamed: 0,Etching_Chamber,Process 3,Temp_Etching,Source_Power,Selectivity,No_Die,Lot_Num,Wafer_Num,Datetime,Thin Film 4,Thin Film 3,Thin Film 2,Thin Film 1
0,0,3,Etching,70.878,50.851,1.047,NOLSM111,1,1,17-02-2019 PM 9:04:30,251.0,267.06,303.82,361.38
1,1,2,Etching,69.561,52.283,1.051,NOLSM212,1,2,17-02-2019 PM 9:04:30,317.0,332.74,369.31,426.11
2,2,1,Etching,70.968,51.610,1.017,NOLSM313,1,3,17-02-2019 PM 9:04:30,411.0,424.21,460.65,517.80
3,3,1,Etching,70.146,51.286,1.027,NOLSM414,1,4,17-02-2019 PM 9:04:30,256.0,272.28,308.56,365.93
4,4,2,Etching,71.174,51.996,1.050,NOLSM515,1,5,17-02-2019 PM 9:04:30,419.0,434.98,471.65,528.85

In [25]:
# 분 당 얼마나 깎여나갔는지 계산
df1_etch['etch_rate']=(df1_etch['Thin Film 1'] - df1_etch['Thin Film 4'] )/40

In [26]:
df1_etch.head()

,Unnamed: 0,Etching_Chamber,Process 3,Temp_Etching,Source_Power,Selectivity,No_Die,Lot_Num,Wafer_Num,Datetime,Thin Film 4,Thin Film 3,Thin Film 2,Thin Film 1,etch_rate
0,0,3,Etching,70.878,50.851,1.047,NOLSM111,1,1,17-02-2019 PM 9:04:30,251.0,267.06,303.82,361.38,2.75950
1,1,2,Etching,69.561,52.283,1.051,NOLSM212,1,2,17-02-2019 PM 9:04:30,317.0,332.74,369.31,426.11,2.72775
2,2,1,Etching,70.968,51.610,1.017,NOLSM313,1,3,17-02-2019 PM 9:04:30,411.0,424.21,460.65,517.80,2.67000
3,3,1,Etching,70.146,51.286,1.027,NOLSM414,1,4,17-02-2019 PM 9:04:30,256.0,272.28,308.56,365.93,2.74825
4,4,2,Etching,71.174,51.996,1.050,NOLSM515,1,5,17-02-2019 PM 9:04:30,419.0,434.98,471.65,528.85,2.74625